name: Master CI Pipeline

on:
  push:
    branches:
      - 'master'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        node: [12]


    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn install --frozen-lockfile --ignore-scripts

      - name: Build Module
        run: yarn build

      - name: Test Module
        run: yarn test
